export const projects = [
  {
    title: 'Student Study Portal',
    description:"This is a fully operational student portal with ability to keep track of homework, todos, look up youtube videos, books, wikipedia, run conversions on things like temperature, mass and length.  Give it a     whirl, though you will have to register a free account to log in to the site. ",
    image: '/images/todo.jpg',
    tags: ['Django', 'Heroku', 'Python', 'HTML', 'CSS'],
    source: 'https://github.com/cutlerwater/student_portal',
    visit: 'https://cw-student-portal.herokuapp.com/',
    id: 0,
  },
  {
    title: 'News and Weather',
    description:"I've combined my news and weather apps.",
    image: '/images/news.png',
    tags: ['Django', 'Heroku', 'Python', 'API', 'CSS'],
    source: 'https://github.com/cutlerwater/newsApp',
    visit: 'https://cutlerwater-newsapp.herokuapp.com/',
    id: 1,
  },
  {
    title: 'Dentist Website',
    description: "Full Dental website for making appointments using Django, HTML, JavaScript and CSS. It was down temporarily but it is back!",
      image: '/images/dental-care.png',
      tags: ['Django', 'Python', 'HTML', 'CSS'],
    source: 'https://github.com/cutlerwater/DentalDjango',
    visit: 'https://dental-template.herokuapp.com/',
    id: 2,
  },
  {
    title: 'Covid Tracker',
    description: "This is a Covid Tracking app I've built using React.JS.",
    image: '/images/covid.png',
    tags: ['React', 'JavaScript', 'HTML'],
    source: 'https://github.com/cutlerwater/CovidTracker',
    visit: 'https://cutlerwater-covid-tracker.netlify.app/',
    id: 3,
  },
  {
    title: 'Gatsby App',
    description: "Another profile site completed but this one is built using Gatsby.JS, GraphQL and markdown pages",
      image: '/images/Gatsby_Contentful.jpg',
      tags: ['GatsbyJS', 'ReactJS', 'JavaScript', 'CSS', 'HTML'],
    source: 'https://github.com/cutlerwater/web-warrior',
    visit: 'https://cutlerwater-gatsby-profile.netlify.app/',
    id: 4,
  },
  {
    title: 'Piano App',
    description: "This is a code repository for my simple piano app.",
      image: '/images/piano.png',
      tags: ['JavaScript', 'CSS', 'HTML'],
    source: 'https://github.com/cutlerwater/SimplePianoApp',
    visit: 'https://cutlerwateritblog.com/WebProjects/Piano/index.html',
    id: 5,
  },
  {
    title: 'CSS Apps',
    description: "This is a collection of small CSS projects ",
      image: '/images/CSSProjects.PNG',
      tags: ['JavaScript', 'CSS', 'HTML'],
    source: 'https://github.com/cutlerwater/CSS-in-28-days',
    visit: 'https://cutlerwateritblog.com/WebProjects/CSSProjects/29daysofCSS/index.html',
    id: 6
  }
];

export const TimeLineData = [
  { year: 2001, text: 'Started my IT journey with my A+ certification', },
  { year: 2002, text: 'Worked as an Installation Tech for the United States Senate', },
  { year: 2005, text: 'Worked as a systems and network engineer for the Social Security Administration', },
  { year: 2010, text: 'Started my SharePoint and web development journey', },
  { year: 2019, text: 'Dove head first into the Power Platform', },
  { year: 2020, text: 'Covid hits and I blast forward', },
  { year: 2021, text: 'Started my own platform', },
];