export const projects = [
  {
    title: 'Responsive themes fun',
    description: "Just a fun little halloween and Christmas web page",
      image: '/images/nativity.jpg',
      tags: [ 'Responsive CSS', 'Vanilla Javascript' 'HTML'],
    source: 'https://github.com/cutlerwater/responsivethemes',
    visit: 'https://cutlerwater-funresponsivethemes.netlify.app/',
    id: 0,
  },
  {
    title: 'Firebase Vue Blog',
    description: "I did it!  I completed the long journey of creating a full blog application and actually deploying it successfully!",
      image: '/images/stock-4.jpg',
      tags: ['VueJS', 'Firebase', 'JavaScript', 'CSS', 'HTML'],
    source: 'https://github.com/cutlerwater/FirebaseBlog',
    visit: 'https://fireblogscutlerwater.web.app/',
    id: 1,
  },
  {
    title: 'Quizzes built with ReactJS',
    description: "I've built a quiz app that has 10 questions based on computers.  I can change the category rather easily as well as other options such as difficulty.  I've also built other quiz subjects like politics, history, math, sports and celebrities",
      image: '/images/cqquiz.PNG',
      tags: ['React', 'APIs', 'Typescript', 'JavaScript', 'CSS', 'HTML'],
    source: 'https://github.com/cutlerwater/react-quizapp',
    visit: 'https://cutlerwater-quizzes.netlify.app/',
    id: 2,
  },
  {
    title: '3d Portfolio',
    description: "I've put together a rather cool 3d based portfolio using more Three JS and some awesome effects",
      image: '/images/AISProfile.jpg',
      tags: ['Three.JS', 'JavaScript', 'CSS', 'HTML'],
    source: 'https://github.com/cutlerwater/threejsportfolio',
    visit: 'https://cutlerwater-3dprofile.netlify.app/',
    id: 3,
  },
  {
    title: '3d Particles',
    description: "I've put together another small project showing the power of three.js.  This one has rotating stars and an animated headline and paragraph",
      image: '/images/3js.jpg',
      tags: ['Three.JS','JavaScript', 'CSS', 'HTML'],
    source: 'https://github.com/cutlerwater/particlesproject',
    visit: 'https://cutlerwater-particlesproject.netlify.app/',
    id: 4,
  },
  {
    title: '3d Rendering of a landscape',
    description: "I've put together a small project showing the power of three.js.  There's a lot of possibilities here.",
      image: '/images/texture.jpg',
      tags: ['Three.JS','JavaScript', 'CSS', 'HTML'],
    source: 'https://github.com/cutlerwater/3dterrain',
    visit: 'https://3dterrain-cutlerwater.netlify.app/',
    id: 5,
  },
  {
    title: 'My own video chat web site!',
    description: "I am putting the blog on hold for now but I have successfully created my own video chat web site.  It's not as fancy as Teams or Zoom or others yet but it works and it's free!",
      image: '/images/3.jpg',
      tags: ['AgoraIO','JavaScript', 'CSS', 'HTML'],
    source: 'https://github.com/cutlerwater/videochat',
    visit: 'https://cutlerwater-vchat.netlify.app/',
    id: 5,
  },  
  {
    title: 'My own standard chat web site!',
    description: "I have also built a standard chat app using React, HTML, a chatenging build, CSS and JS.  I do not have a way to create a user easily and I can only have 25 users max but it works well.",
      image: '/images/chat.png',
      tags: ['React','JavaScript', 'CSS', 'HTML'],
    source: 'https://github.com/cutlerwater/ReactChat',
    visit: 'https://cutlerwater-chat.netlify.app/',
    id: 6,
  }, 
  {
    title: 'Student Study Portal',
    description:"This is a fully operational student portal with ability to keep track of homework, todos, look up youtube videos, books, wikipedia, run conversions on things like temperature, mass and length.  Give it a     whirl, though you will have to register a free account to log in to the site. ",
    image: '/images/todo.jpg',
    tags: ['Django', 'Heroku', 'Python', 'HTML', 'CSS'],
    source: 'https://github.com/cutlerwater/student_portal',
    visit: 'https://cw-student-portal.herokuapp.com/',
    id: 7,
  },
  {
    title: 'My Flask Resume',
    description:"I've put together a new Resume app using Flask and Python.",
    image: '/images/Resume.png',
    tags: ['Flask', 'Heroku', 'Python', 'HTML', 'JS', 'CSS'],
    source: 'https://github.com/cutlerwater/ResumeFlash/',
    visit: 'https://my-cutlerwaterresume.herokuapp.com/',
    id: 8,
  },
  {
    title: 'News and Weather',
    description:"I've combined my news and weather apps, along with a BBC news page.",
    image: '/images/news.png',
    tags: ['Django', 'Heroku', 'Python', 'API', 'CSS'],
    source: 'https://github.com/cutlerwater/news-django',
    visit: 'https://cutlerwater-news.herokuapp.com/',
    id: 9,
  },
  {
    title: 'Dentist Website',
    description: "Full Dental website for making appointments using Django, HTML, JavaScript and CSS. It was down temporarily but it is back!",
      image: '/images/dental-care.png',
      tags: ['Django', 'Python', 'HTML', 'CSS'],
    source: 'https://github.com/cutlerwater/DentalDjango',
    visit: 'https://dental-template.herokuapp.com/',
    id: 10,
  },
  {
    title: 'Cutlerwater-IMDB',
    description: "This is my own personal imdb like site that I built using ReactJS using a API key to retrieve the information.  WARNING!!! This site can search for just about ANY movie(s), so it may not be safe for work or kids, depending on what they search for.",
    image: '/images/movieimdb.PNG',
    tags: ['React', 'JavaScript', 'HTML'],
    source: 'https://github.com/cutlerwater/imdb-react',
    visit: 'https://cutlerwater-movieimdb.netlify.app/',
    id: 11,
  },
  {
    title: 'Covid Tracker',
    description: "This is a Covid Tracking app I've built using React.JS.",
    image: '/images/covid.png',
    tags: ['React', 'JavaScript', 'HTML'],
    source: 'https://github.com/cutlerwater/CovidTracker',
    visit: 'https://cutlerwater-covid-tracker.netlify.app/',
    id: 12,
  },
  {
    title: 'Gatsby App',
    description: "Another profile site completed but this one is built using Gatsby.JS, GraphQL and markdown pages",
      image: '/images/Gatsby_Contentful.jpg',
      tags: ['GatsbyJS', 'ReactJS', 'JavaScript', 'CSS', 'HTML'],
    source: 'https://github.com/cutlerwater/web-warrior',
    visit: 'https://cutlerwater-gatsby-profile.netlify.app/',
    id: 13,
  },
  {
    title: 'Skeleton Website Designs',
    description: "I put together 10 website designs covering 10 different areas ranging from shoes to technology and more.  They don't have a lot of purpose at this time but could serve as starter projects later on. ",
      image: '/images/img-3.jpg',
      tags: ['JavaScript', 'CSS', 'HTML'],
    source: 'https://github.com/cutlerwater/automotive-car-design',
    visit: 'https://cutlerwater-automotive-car-webdesign.netlify.app/',
    id: 14,
  }, 
  {
    title: 'Beautiful curves website',
    description: "I couldn't fully deploy a 3d project I was working on for a while and since I vowed to myself to deploy something, I deployed this simple html/css project with a cool template with curves in it.",
      image: '/images/curves.png',
      tags: ['JavaScript', 'CSS', 'HTML'],
    source: 'https://github.com/cutlerwater/curves',
    visit: 'https://curves-cutlerwater.netlify.app/',
    id: 15,
  }, 
  
];

export const TimeLineData = [
  { year: 2001, text: 'Started my IT journey with my A+ certification', },
  { year: 2002, text: 'Worked as an Installation Tech for the United States Senate', },
  { year: 2005, text: 'Worked as a systems and network engineer for the Social Security Administration', },
  { year: 2010, text: 'Started my SharePoint and web development journey', },
  { year: 2019, text: 'Dove head first into the Power Platform', },
  { year: 2020, text: 'Covid hits and I blast forward', },
  { year: 2021, text: 'Started my own platform', },
];